#!/usr/bin/env python3
"""Regenerate docs/decisions-index.md from the post-fold docs/DECISIONS.md.

Deterministic, stdlib-only. One line per entry (all of D3..D182, incl. -confirm
addenda):  D### · <headline> · RULING|journal → git <hash>
RULING  = kept full-text in docs/DECISIONS.md.
journal = folded to a stub there; body lives in git history at <hash>.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from split_ledger import LEDGER, REPO, entry_hash, parse  # noqa: E402

INDEX = REPO / "docs" / "decisions-index.md"
STUB_RE = re.compile(r"^(D(\d{1,3})(?:-[A-Za-z0-9]+)?) (.*) → git (\S+)$")


def main() -> None:
    header, entries, archive = parse(LEDGER.read_text(encoding="utf-8"))

    rows = []  # (num, entry_id, line)
    for eid, num, headline, _seg in entries:
        rows.append((num, eid, f"{eid} · {headline} · RULING → git {entry_hash(eid)}"))
    for line in archive.splitlines():
        m = STUB_RE.match(line)
        if not m:
            continue
        eid, num, headline, ghash = m.group(1), int(m.group(2)), m.group(3), m.group(4)
        rows.append((num, eid, f"{eid} · {headline} · journal → git {ghash}"))

    rows.sort(key=lambda r: (r[0], r[1]))
    nums = {n for n, _, _ in rows}
    expected = set(range(min(nums), max(nums) + 1))
    missing = expected - nums
    if missing:
        raise SystemExit(f"index would be missing D#s: {sorted(missing)}")

    out = (
        "<!-- GENERATED by scripts/gen_decisions_index.py — do not hand-edit. -->\n"
        "<!-- D### · headline · RULING (kept full-text) | journal (stub) → git <hash> -->\n\n"
        + "\n".join(line for _, _, line in rows)
        + "\n"
    )
    INDEX.write_text(out, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(REPO)}: {len(rows)} lines, "
          f"D{min(nums)}..D{max(nums)} complete")


if __name__ == "__main__":
    sys.exit(main())
